#:schema node_modules/wrangler/config-schema.json
name = "referrals-service"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true


# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
# [[d1_databases]]
# binding = "MY_DB"
# database_name = "my-database"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"


[[d1_databases]]
binding = "REFERRALS"
database_name = "referrals"
database_id = "65fdb889-7f6a-4cf7-b12a-3272ee730504"
preview_database_id = "REFERRALS"

[[env.staging.d1_databases]]
binding = "REFERRALS"
database_name = "referrals"
database_id = "96dc4903-fd46-4a1b-a6ef-96060c198f7b"

[[env.production.d1_databases]]
binding = "REFERRALS"
database_name = "referrals"
database_id = "783a91d6-63ae-454b-8f26-ac015e862376"

[vars]
ALLOW_ORIGIN = "http://localhost:3004"

[env.staging.vars] 
ALLOW_ORIGIN = "https://staging.console.storacha.network"

[env.production.vars] 
ALLOW_ORIGIN = "https://console.storacha.network"